# Site settings
title: Data Science Engine
longtitle: Data Science Engine (blog by Rohan Kotwani)
email: rohankotwani@icloud.com
description: Data Science Engine â€” A showcase of algorithms written from scratch
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://freedomtowin.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: freedomtowin
# Build settings
markdown: kramdown
